# Brew Core
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Development Tools
brew "git"
brew "curl"
brew "bash-completion"
brew "zsh-autosuggestions"
brew "tmux"
brew "neovim"
brew "ripgrep"
brew "gnupg"
brew "kubernetes-cli"

# Development - Go
brew "go"

# Development - Rust
brew "rustup-init"

# Development - TypeScript
brew "yarn"

# Markdown
brew "glow"

# MacOS Applications
cask "middle"
cask "brave-browser"
cask "google-chrome"
cask "firefox"
cask "spotify"
cask "visual-studio-code"
